// -------------- SIGN UP -------------------
export const SIGN_UP_PENDING = "SIGN_UP_PENDING";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
// -------------- SIGN IN -------------------
export const SIGN_IN_PENDING = "SIGN_IN_PENDING";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
// -------------- SIGN OUT -------------------
export const SIGN_OUT_PENDING = "SIGN_OUT_PENDING";
export const SIGN_OUT_ERROR = "SIGN_OUT_ERROR";
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
export const UPDATE_AUTH = "UPDATE_AUTH";
